/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentIndexRouteImport } from './routes/content/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as TestIdRouteImport } from './routes/test/$id'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AccountTesterRequestRouteImport } from './routes/account/tester-request'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as AccountGameRouteImport } from './routes/account/game'
import { Route as ContentTypeSlugRouteImport } from './routes/content/$type.$slug'
import { Route as ApiDownloadPatcherInfoRouteImport } from './routes/api/download/patcher-info'
import { Route as ApiDownloadPatcherRouteImport } from './routes/api/download/patcher'
import { Route as ApiPublicContentIndexRouteImport } from './routes/api/public/content/index'
import { Route as ApiPublicContentIdRouteImport } from './routes/api/public/content/$id'
import { Route as ApiPatcherAuthRefreshRouteImport } from './routes/api/patcher/auth/refresh'
import { Route as ApiPatcherAuthMeRouteImport } from './routes/api/patcher/auth/me'
import { Route as ApiPatcherAuthLoginRouteImport } from './routes/api/patcher/auth/login'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIdRoute = TestIdRouteImport.update({
  id: '/test/$id',
  path: '/test/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountTesterRequestRoute = AccountTesterRequestRouteImport.update({
  id: '/account/tester-request',
  path: '/account/tester-request',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountGameRoute = AccountGameRouteImport.update({
  id: '/account/game',
  path: '/account/game',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentTypeSlugRoute = ContentTypeSlugRouteImport.update({
  id: '/content/$type/$slug',
  path: '/content/$type/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadPatcherInfoRoute = ApiDownloadPatcherInfoRouteImport.update({
  id: '/api/download/patcher-info',
  path: '/api/download/patcher-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadPatcherRoute = ApiDownloadPatcherRouteImport.update({
  id: '/api/download/patcher',
  path: '/api/download/patcher',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContentIndexRoute = ApiPublicContentIndexRouteImport.update({
  id: '/api/public/content/',
  path: '/api/public/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContentIdRoute = ApiPublicContentIdRouteImport.update({
  id: '/api/public/content/$id',
  path: '/api/public/content/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatcherAuthRefreshRoute = ApiPatcherAuthRefreshRouteImport.update({
  id: '/api/patcher/auth/refresh',
  path: '/api/patcher/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatcherAuthMeRoute = ApiPatcherAuthMeRouteImport.update({
  id: '/api/patcher/auth/me',
  path: '/api/patcher/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatcherAuthLoginRoute = ApiPatcherAuthLoginRouteImport.update({
  id: '/api/patcher/auth/login',
  path: '/api/patcher/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/game': typeof AccountGameRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/tester-request': typeof AccountTesterRequestRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/test/$id': typeof TestIdRoute
  '/account': typeof AccountIndexRoute
  '/content': typeof ContentIndexRoute
  '/api/download/patcher': typeof ApiDownloadPatcherRoute
  '/api/download/patcher-info': typeof ApiDownloadPatcherInfoRoute
  '/content/$type/$slug': typeof ContentTypeSlugRoute
  '/api/patcher/auth/login': typeof ApiPatcherAuthLoginRoute
  '/api/patcher/auth/me': typeof ApiPatcherAuthMeRoute
  '/api/patcher/auth/refresh': typeof ApiPatcherAuthRefreshRoute
  '/api/public/content/$id': typeof ApiPublicContentIdRoute
  '/api/public/content': typeof ApiPublicContentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/game': typeof AccountGameRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/tester-request': typeof AccountTesterRequestRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/test/$id': typeof TestIdRoute
  '/account': typeof AccountIndexRoute
  '/content': typeof ContentIndexRoute
  '/api/download/patcher': typeof ApiDownloadPatcherRoute
  '/api/download/patcher-info': typeof ApiDownloadPatcherInfoRoute
  '/content/$type/$slug': typeof ContentTypeSlugRoute
  '/api/patcher/auth/login': typeof ApiPatcherAuthLoginRoute
  '/api/patcher/auth/me': typeof ApiPatcherAuthMeRoute
  '/api/patcher/auth/refresh': typeof ApiPatcherAuthRefreshRoute
  '/api/public/content/$id': typeof ApiPublicContentIdRoute
  '/api/public/content': typeof ApiPublicContentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/game': typeof AccountGameRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/tester-request': typeof AccountTesterRequestRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/test/$id': typeof TestIdRoute
  '/account/': typeof AccountIndexRoute
  '/content/': typeof ContentIndexRoute
  '/api/download/patcher': typeof ApiDownloadPatcherRoute
  '/api/download/patcher-info': typeof ApiDownloadPatcherInfoRoute
  '/content/$type/$slug': typeof ContentTypeSlugRoute
  '/api/patcher/auth/login': typeof ApiPatcherAuthLoginRoute
  '/api/patcher/auth/me': typeof ApiPatcherAuthMeRoute
  '/api/patcher/auth/refresh': typeof ApiPatcherAuthRefreshRoute
  '/api/public/content/$id': typeof ApiPublicContentIdRoute
  '/api/public/content/': typeof ApiPublicContentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/account/game'
    | '/account/settings'
    | '/account/tester-request'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/test/$id'
    | '/account'
    | '/content'
    | '/api/download/patcher'
    | '/api/download/patcher-info'
    | '/content/$type/$slug'
    | '/api/patcher/auth/login'
    | '/api/patcher/auth/me'
    | '/api/patcher/auth/refresh'
    | '/api/public/content/$id'
    | '/api/public/content'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/account/game'
    | '/account/settings'
    | '/account/tester-request'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/test/$id'
    | '/account'
    | '/content'
    | '/api/download/patcher'
    | '/api/download/patcher-info'
    | '/content/$type/$slug'
    | '/api/patcher/auth/login'
    | '/api/patcher/auth/me'
    | '/api/patcher/auth/refresh'
    | '/api/public/content/$id'
    | '/api/public/content'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/account/game'
    | '/account/settings'
    | '/account/tester-request'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/test/$id'
    | '/account/'
    | '/content/'
    | '/api/download/patcher'
    | '/api/download/patcher-info'
    | '/content/$type/$slug'
    | '/api/patcher/auth/login'
    | '/api/patcher/auth/me'
    | '/api/patcher/auth/refresh'
    | '/api/public/content/$id'
    | '/api/public/content/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DownloadRoute: typeof DownloadRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AccountGameRoute: typeof AccountGameRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountTesterRequestRoute: typeof AccountTesterRequestRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  TestIdRoute: typeof TestIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ContentIndexRoute: typeof ContentIndexRoute
  ApiDownloadPatcherRoute: typeof ApiDownloadPatcherRoute
  ApiDownloadPatcherInfoRoute: typeof ApiDownloadPatcherInfoRoute
  ContentTypeSlugRoute: typeof ContentTypeSlugRoute
  ApiPatcherAuthLoginRoute: typeof ApiPatcherAuthLoginRoute
  ApiPatcherAuthMeRoute: typeof ApiPatcherAuthMeRoute
  ApiPatcherAuthRefreshRoute: typeof ApiPatcherAuthRefreshRoute
  ApiPublicContentIdRoute: typeof ApiPublicContentIdRoute
  ApiPublicContentIndexRoute: typeof ApiPublicContentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/': {
      id: '/content/'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$id': {
      id: '/test/$id'
      path: '/test/$id'
      fullPath: '/test/$id'
      preLoaderRoute: typeof TestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/tester-request': {
      id: '/account/tester-request'
      path: '/account/tester-request'
      fullPath: '/account/tester-request'
      preLoaderRoute: typeof AccountTesterRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/game': {
      id: '/account/game'
      path: '/account/game'
      fullPath: '/account/game'
      preLoaderRoute: typeof AccountGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$type/$slug': {
      id: '/content/$type/$slug'
      path: '/content/$type/$slug'
      fullPath: '/content/$type/$slug'
      preLoaderRoute: typeof ContentTypeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/patcher-info': {
      id: '/api/download/patcher-info'
      path: '/api/download/patcher-info'
      fullPath: '/api/download/patcher-info'
      preLoaderRoute: typeof ApiDownloadPatcherInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/patcher': {
      id: '/api/download/patcher'
      path: '/api/download/patcher'
      fullPath: '/api/download/patcher'
      preLoaderRoute: typeof ApiDownloadPatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/content/': {
      id: '/api/public/content/'
      path: '/api/public/content'
      fullPath: '/api/public/content'
      preLoaderRoute: typeof ApiPublicContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/content/$id': {
      id: '/api/public/content/$id'
      path: '/api/public/content/$id'
      fullPath: '/api/public/content/$id'
      preLoaderRoute: typeof ApiPublicContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patcher/auth/refresh': {
      id: '/api/patcher/auth/refresh'
      path: '/api/patcher/auth/refresh'
      fullPath: '/api/patcher/auth/refresh'
      preLoaderRoute: typeof ApiPatcherAuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patcher/auth/me': {
      id: '/api/patcher/auth/me'
      path: '/api/patcher/auth/me'
      fullPath: '/api/patcher/auth/me'
      preLoaderRoute: typeof ApiPatcherAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patcher/auth/login': {
      id: '/api/patcher/auth/login'
      path: '/api/patcher/auth/login'
      fullPath: '/api/patcher/auth/login'
      preLoaderRoute: typeof ApiPatcherAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DownloadRoute: DownloadRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AccountGameRoute: AccountGameRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountTesterRequestRoute: AccountTesterRequestRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  TestIdRoute: TestIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  ContentIndexRoute: ContentIndexRoute,
  ApiDownloadPatcherRoute: ApiDownloadPatcherRoute,
  ApiDownloadPatcherInfoRoute: ApiDownloadPatcherInfoRoute,
  ContentTypeSlugRoute: ContentTypeSlugRoute,
  ApiPatcherAuthLoginRoute: ApiPatcherAuthLoginRoute,
  ApiPatcherAuthMeRoute: ApiPatcherAuthMeRoute,
  ApiPatcherAuthRefreshRoute: ApiPatcherAuthRefreshRoute,
  ApiPublicContentIdRoute: ApiPublicContentIdRoute,
  ApiPublicContentIndexRoute: ApiPublicContentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
